version: '3'

services:
  s_vuejs:
    env_file: ./.env

    build:
      context: .
      args:
        workdir: $client_workdir
    ports:
      - $client_port:$client_port
    volumes:
      - .:$client_workdir
      - v_vuejs:$client_workdir/node_modules

volumes:
  v_vuejs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
